name: Lint and Type Check

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint-and-type-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check ESLint and Prettier rules
        run: npm run check

      - name: Run build to verify compilation
        run: npm run build
